/* defines a possible list of moves that certain pieces are able to make */
#define UNIDIRECTIONAL_MOVE_ONE_SPACE_FORWARDS           1
#define BIDIRECTIONAL_MOVE_ONE_SPACE_DIAGONAL_FORWARDS   2
#define MULTIDIRECTIONAL_MOVE_ONE_SPACES                 3
#define UNIDIRECTIONAL_MOVE_TWO_SPACES_FORWARDS          4
#define BIDIRECTIONAL_VERTICAL_MOVE_ONE_OR_MORE_SPACES   5
#define BIDIRECTIONAL_HORIZONTAL_MOVE_ONE_OR_MORE_SPACES 6
#define BIDIRECTIONAL_45_OR_225_DEGREES_MOVE_ONE_OR_MORE_SPACES    7
#define BIDIRECTIONAL_135_OR_315_DEGREE_MOVE_ONE_OR_MORE_SPACES    8
#define L_SHAPE_MOVE_CAN_JUMP_PIECES                     9
#define INVALID_MOVE                                     0



